server {
    listen 80;
    listen [::]:80;
    server_name zion-garden.be www.zion-garden.be;

    root /var/www/zion-garden;
    index index.html;

    location / {
        try_files $uri $uri/ =404;
    }

    location = /robots.txt { access_log off; }
    location = /favicon.ico { access_log off; log_not_found off; }
}
